core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.get_main_page, name='main'),

    path('publications/', views.PublicationList.as_view(), name='publications'),
    path('publication_detail/<int:pk>', views.PublicationDetail.as_view(), name='publication_detail'),
    path('publication_create', views.PublicationCreate.as_view(), name='publication_create'),
    path('publication_update/<int:pk>', views.PublicationUpdate.as_view(), name='publication_update'),
    path('publication_delete/<int:pk>', views.PublicationDelete.as_view(), name='publication_delete'),
    path('publication_like/<int:pk>', views.publication_like, name="publication_like"),
    path('publication_comment/<int:pk>', views.PublicationCommentCreate.as_view(), name="publication_comment"),
    path('publication_comment_delete/<int:pk>', views.PublicationCommentDelete.as_view(), name='publication_comment_delete'),

    path('persons/', views.PersonList.as_view(), name='persons'),
    path('person_detail/<int:pk>', views.PersonDetail.as_view(), name='person_detail'),
    path('person_create', views.PersonCreate.as_view(), name='person_create'),
    path('person_update/<int:pk>', views.PersonUpdate.as_view(), name='person_update'),
    path('person_delete/<int:pk>', views.PersonDelete.as_view(), name='person_delete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('profiles/', views.ProfileList.as_view(), name='profiles'),
    path('user_update/', views.UserUpdate.as_view(), name='user_update'),
    path('user_profile/<int:pk>', views.ProfileDetail.as_view(), name='user_profile'),
    path('user_profile_create', views.ProfileCreate.as_view(), name='user_profile_create'),
    path('user_profile_update', views.ProfileUpdate.as_view(), name='user_profile_update'),
    path('user_profile_delete/<int:pk>', views.ProfileDelete.as_view(), name='user_profile_delete'),
    path('user_profile_change_role/<int:pk>', views.ProfileChangeRole.as_view(), name='user_profile_change_role'),

    path('logout/', views.logout_user, name='logout'),
]

itcode_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User

from core import models


class PublicationForm(forms.ModelForm):

    # постараться сократить эти проверки и соблюсти DRY
    def clean_title(self):
        title = self.cleaned_data['title']
        if title.isdigit():
            raise forms.ValidationError('Название публикации не должно состоять только из чисел')
        return title

    def clean_content(self):
        content = self.cleaned_data['content']
        if content.isdigit():
            raise forms.ValidationError('Содержание публикации некорректно')
        return content

    class Meta:
        model = models.Publication
        fields = ('title', 'content', 'theme', 'category', 'person', 'year_start', 'year_end', 'photo',
                  'is_published',)
        # fields = "__all__"


class PersonForm(forms.ModelForm):

    # постараться сократить эти проверки и соблюсти DRY
    def clean_name(self):
        name = self.cleaned_data['name']
        if name.isdigit():
            raise forms.ValidationError('Некорректное имя')
        return name

    def clean_surname(self):
        surname = self.cleaned_data['surname']
        if surname.isdigit():
            raise forms.ValidationError('Некорректная фамилия')
        return surname

    def clean_patronymic(self):
        patronymic = self.cleaned_data['patronymic']
        if patronymic.isdigit():
            raise forms.ValidationError('Некорректное отчество')
        return patronymic

    def clean_bio(self):
        bio = self.cleaned_data['bio']
        if bio.isnumeric():
            raise forms.ValidationError('Некорректная биография')
        return bio

    class Meta:
        model = models.Person
        fields = ('name', 'surname', 'patronymic', 'birthday', 'deathday', 'photo', 'bio',)


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserUpdateForm(UserChangeForm):
    email = forms.EmailField(label='Почта', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('email', 'password',)


class UserUpdateProfileForm(UserChangeForm):
    nickname = forms.CharField(label='Никнейм', widget=forms.TextInput(attrs={'class': 'form-input'}))
    status = forms.CharField(label='Статус', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = models.Profile
        fields = ('nickname', 'profile_photo', 'status',)


class UserCreateProfileForm(forms.ModelForm):
    nickname = forms.CharField(label='Никнейм', widget=forms.TextInput(attrs={'class': 'form-input'}))
    status = forms.CharField(label='Статус', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = models.Profile
        fields = ('nickname', 'profile_photo', 'status',)


class PublicationCreatComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('body', 'image', 'parent', )
        # fields = "__all__"


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

core/views.py
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from core import models, datatools, forms, filters
from core.datatools.index import TitleMixin
from django.shortcuts import render


class PublicationList(TitleMixin, ListView):
    model = models.Publication
    template_name = 'core/publication_list.html'
    context_object_name = 'publications'
    title = 'Все публикации'

    def get_filters(self):
        return filters.PublicationSearch(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filters()
        return context


class PublicationDetail(TitleMixin, DetailView):
    model = models.Publication
    template_name = 'core/publication_detail.html'
    context_object_name = 'publication'
    title = 'Полная публикация'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        likes_connected = get_object_or_404(models.Publication, id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True
        data['number_of_likes'] = likes_connected.number_of_likes()
        data['post_is_liked'] = liked
        return data


def publication_like(request, pk):
    post = get_object_or_404(models.Publication, id=request.POST.get('publication_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return HttpResponseRedirect(reverse('core:publication_detail', args=[str(pk)]))


class PublicationCreate(TitleMixin, CreateView):
    model = models.Publication
    template_name = 'core/publication_create.html'
    form_class = forms.PublicationForm
    title = 'Создание публикации'
    success_url = reverse_lazy('core:publications')

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)


class PublicationUpdate(TitleMixin, UpdateView):
    model = models.Publication
    template_name = 'core/publication_update.html'
    form_class = forms.PublicationForm
    title = 'Обновление публикации'
    success_url = reverse_lazy('core:publications')


class PublicationDelete(TitleMixin, DeleteView):
    model = models.Publication
    template_name = 'core/publication_delete.html'
    fields = "__all__"
    title = 'Удаление публикации'
    success_url = reverse_lazy('core:publications')


class PublicationCommentCreate(TitleMixin, CreateView):
    template_name = 'core/publication_comment_create.html'
    form_class = forms.PublicationCreatComment
    title = 'Комментарий'
    success_url = reverse_lazy('core:publications')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        form.instance.publication_id = self.kwargs['pk']
        return super().form_valid(form)


class PublicationCommentDelete(TitleMixin, DeleteView):
    model = models.Comment
    template_name = 'core/publication_comment_delete.html'
    fields = "__all__"
    title = 'Удаление комментария'
    success_url = reverse_lazy('core:publications')


class PersonList(TitleMixin, ListView):
    model = models.Person
    template_name = 'core/person_list.html'
    context_object_name = 'persons'
    title = 'Список личностей'

    def get_filters(self):
        return filters.PersonSearch(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filters()
        return context


class PersonDetail(TitleMixin, DetailView):
    model = models.Person
    template_name = 'core/person_detail.html'
    context_object_name = 'person'
    title = 'Подробнее о личности'


class PersonCreate(TitleMixin, CreateView):
    model = models.Person
    template_name = 'core/person_create.html'
    form_class = forms.PersonForm
    title = 'Добавление личности'
    success_url = reverse_lazy('core:persons')

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)


class PersonUpdate(TitleMixin, UpdateView):
    model = models.Person
    template_name = 'core/person_update.html'
    form_class = forms.PersonForm
    title = 'Обновление данных о личности'
    success_url = reverse_lazy('core:persons')


class PersonDelete(TitleMixin, DeleteView):
    model = models.Person
    template_name = 'core/person_delete.html'
    fields = "__all__"
    title = 'Удаление личности'
    success_url = reverse_lazy('core:persons')


def get_main_page(request):
    return render(request=request, template_name='core/main.html')


class RegisterUser(TitleMixin, CreateView):
    title = 'Регистрация'
    form_class = forms.RegisterUserForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:main')


class LoginUser(TitleMixin, LoginView):
    title = 'Авторизация'
    form_class = forms.LoginUserForm
    template_name = 'core/login.html'

    def get_success_url(self):
        return reverse_lazy('core:main')


class UserUpdate(TitleMixin, UpdateView):
    title = 'Настройки'
    form_class = forms.UserUpdateForm
    template_name = 'core/user_update.html'
    success_url = reverse_lazy('core:user_update')

    def get_object(self):
        return self.request.user


class ProfileDetail(TitleMixin, DetailView):
    model = models.Profile
    template_name = 'core/user_profile.html'
    context_object_name = 'profile'
    title = 'Профиль'


class ProfileUpdate(TitleMixin, UpdateView):
    model = models.Profile
    title = 'Изменение профиля'
    form_class = forms.UserUpdateProfileForm
    template_name = 'core/user_profile_update.html'
    success_url = reverse_lazy('core:user_profile_update')

    def get_object(self):
        return self.request.user.profile


class ProfileCreate(TitleMixin, CreateView):
    models = models.Profile
    title = 'Создание профиля'
    form_class = forms.UserCreateProfileForm
    template_name = 'core/user_profile_create.html'
    success_url = reverse_lazy('core:user_profile_update')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProfileList(TitleMixin, ListView):
    model = models.Profile
    template_name = 'core/user_profile_list.html'
    context_object_name = 'profiles'
    title = 'Профили'

    def get_filters(self):
        return filters.ProfileSearch(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filters()
        return context


class ProfileDelete(TitleMixin, DeleteView):
    model = models.Profile
    template_name = 'core/user_profile_delete.html'
    fields = "__all__"
    title = 'Удаление профиля'
    success_url = reverse_lazy('core:profiles')


class ProfileChangeRole(TitleMixin, UpdateView):
    model = models.User
    template_name = 'core/user_profile_change_role.html'
    fields = ('is_staff', 'is_superuser',)
    title = 'Смена прав'
    success_url = reverse_lazy('core:profiles')


def logout_user(request):
    logout(request)
    return redirect('core:main')

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
{% if request.user.is_authenticated %}
    <a class="btn btn-info" href="{% url 'core:main' %}" role="button">Главная</a>
    <a class="btn btn-secondary" href="{% url 'core:persons' %}" role="button">Исторические личности</a>
    <a class="btn btn-dark" href="{% url 'core:publications' %}" role="button">Публикации</a>
    <a class="btn btn-warning" href="{% url 'core:user_update' %}" role="button">Настройки пользователя</a>
    {% if user.profile.pk %}
        <a class="btn btn-info" href="{% url 'core:user_profile_update' %}" role="button">Настройки профиля</a>
        <a class="btn btn-success" href="{% url 'core:user_profile' pk=user.profile.pk %}" role="button">Мой профиль</a>
        <a class="btn btn-warning" href="{% url 'core:profiles' %}" role="button">Поиск пользователей</a>
    {% else %}
        <a class="btn btn-info" href="{% url 'core:user_profile_create' %}" role="button">Создать профиль</a>
    {% endif %}
{% endif %}
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %} Главная {% endblock %}
{% block content %}
    <h1>Авторизация</h1>
    <form method="post">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <button class="btn btn-success" type="submit">Авторизоваться</button>
        <a class="btn btn-secondary" href="{% url 'core:main' %}" role="button">Отмена</a>
    </form>
{% endblock %}

core/templates/core/person_create.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser or request.user.is_staff%}
    {% block title %} {{ title }} {% endblock %}
    {% block content %}
        <h1>Добавление исторической личности</h1>
        <form action="{% url 'core:person_create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Добавить</button>
            <a class="btn btn-secondary" href="{% url 'core:persons' %}" role="button">Вернуться к личностям</a>
        </form>
    {% endblock %}
{% endif %}

core/templates/core/person_delete.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser %}
    {% block title %} {{ title }} {% endblock %}
    {% block content %}
        <h1>Удалить личность {{ person.name.title }} {{ person.surname.title }}?</h1>
        <form action="{% url 'core:person_delete' pk=person.pk %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-danger" type="submit">Удалить</button>
            <a class="btn btn-secondary" href="{% url 'core:persons' %}" role="button">Вернуться к личностям</a>
        </form>
    {% endblock %}
{% endif %}

core/templates/core/person_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <br>
    <br>
    <a class="btn btn-secondary" onclick="history.back()" role="button">Назад</a>
    <h1>Информация об исторической
        личности: {{ person.name.title }} {{ person.surname.title }} {{ person.patronymic.title }}</h1>
    {% if person.photo.url != Null %}
        <img src="{{ person.photo.url }}" width="400" height="400">
    {% else %}
        <img src="{% static 'core/images/findphoto.png' %}" width="400" height="400">
    {% endif %}
    {% if request.user.is_superuser %}
        <h3>ID: {{ person.pk }}</h3>
    {% endif %}
    <h3>Годы жизни: {{ person.birthday }} - {{ person.deathday }}</h3>
    <h3>Связанные статьи:</h3>
    {% for publication in person.persons.all %}
        <ul>
            <li><a href="{% url 'core:publication_detail' publication.pk %}"
                   role="button"> {{ publication }}</a></li>
        </ul>
    {% empty %}
        <h2>Связанных статей нет</h2>
    {% endfor %}
    <h3>Биография:</h3>
    {{ person.bio|linebreaks }}
{% endblock %}

core/templates/core/person_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}<
{% block content %}
        <h1>Список исторических личностей</h1>
        <form method="GET">
            {{ filter.form.as_p }}
            <button class="btn btn-warning btn-sm" type="submit" role="button">Поиск</button>
            <a class="btn btn-secondary btn-sm" href="{% url 'core:persons' %}" role="button">Сброс</a>
        </form>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID исторической личности</th>
                <th scope="col">Изображение</th>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Отчество</th>
                <th scope="col">Годы жизни</th>
                <th scope="col">Автор</th>
                <th scope="col">Связанные статьи</th>
                <th scope="col">Дата добавления</th>
                <th scope="col">Дата обновления</th>
                <th scope="col">Подробнее</th>
                {% if request.user.is_superuser or request.user.is_staff%}
                    <th scope="col">Обновление</th>
                {% elif request.user.is_superuser %}
                    <th scope="col">Удаление</th>
                {% endif %}
            </tr>
            </thead>
            {% for person in persons %}
                <tbody>
                <tr>
                    <td>{{ person.pk }}</td>
                    {% if person.photo.url != Null %}
                        <td><img src="{{ person.photo.url }}" class="img-thumbnail" width="200" height="200">
                        </td>
                    {% else %}
                        <td><img src="{% static 'core/images/findphoto.png' %}" width="200" height="200"></td>
                    {% endif %}
                    <td>{{ person.name.title }}</td>
                    <td>{{ person.surname.title }}</td>
                    <td>{{ person.patronymic.title }}</td>
                    <td>{{ person.birthday }} - {{ person.deathday }}</td>
                    {##}
                    <td><a href="{% url 'core:user_profile' person.author.pk %}"
                           role="button"> {{ person.author }}</a></td>

                    <td>{% if person.persons.all %}
                        {{ person.persons.all.count }}
                    {% else %}
                        Связанных статей нет
                    {% endif %}</td>


                    <td>{{ person.time_publish|date:"d-m-Y H:i:s" }}</td>
                    <td>{{ person.time_update|date:"d-m-Y H:i:s" }}</td>
                    <td><a href="{% url 'core:person_detail' person.pk %}" role="button">Подробнее</a></td>
                    {% if request.user.is_superuser or request.user.is_staff %}
                        <td><a href="{% url 'core:person_update' person.pk %}" role="button">Обновление информации</a>
                        </td>
                        {% elif request.user.is_superuser %}
                        <td><a href="{% url 'core:person_delete' person.pk %}" role="button">Удаление</a>
                        </td>
                    {% endif %}
                </tr>
                </tbody>
            {% empty %}
                <h3>Список пуст</h3>
            {% endfor %}
        </table>
        {% if request.user.is_superuser %}
            <a class="btn btn-primary" href="{% url 'core:person_create' %}" role="button">Добавление новой личности</a>
        {% endif %}
{% endblock %}

core/templates/core/person_update.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser or request.user.is_staff %}
    {% block title %} {{ title }} {% endblock %}
    {% block content %}
        <h1>Обновление информации о
            личности {{ person.name.title }} {{ person.surname.title }} {{ person.patronymic.title }}</h1>
        <form action="{% url 'core:person_update' pk=person.pk %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Обновить</button>
            <a class="btn btn-secondary" href="{% url 'core:persons' %}" role="button">Вернуться</a>
        </form>
    {% endblock %}
{% endif %}

core/templates/core/publication_create.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser or request.user.is_staff %}
    {% block title %} {{ title }} {% endblock %}<
    {% block content %}
        <h1>Создание публикации</h1>
        <form action="{% url 'core:publication_create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Создать</button>
            <a class="btn btn-secondary" href="{% url 'core:publications' %}" role="button">Вернуться к публикациям</a>
        </form>
    {% endblock %}
{% endif %}

core/templates/core/publication_delete.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser %}
    {% block title %} {{ title }} {% endblock %}<
    {% block content %}
        <h1>Удалить публикацию "{{ publication.title }}"?</h1>
        <form action="{% url 'core:publication_delete' pk=publication.pk %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-danger" type="submit">Удалить публикацию</button>
            <a class="btn btn-secondary" href="{% url 'core:publications' %}" role="button">Вернуться к публикациям</a>
        </form>
    {% endblock %}
{% endif %}

core/templates/core/publication_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <br>
    <br>
    <a class="btn btn-secondary" onclick="history.back()" role="button">Назад</a>
    <h1>"{{ publication.title }}"</h1>
    {% if publication.photo.url != Null %}
        <img src="{{ publication.photo.url }}" width="400" height="400">
    {% else %}
        <img src="{% static 'core/images/findphoto.png' %}" width="400" height="400">
    {% endif %}
    <h3>ID: {{ publication.pk }}</h3>
    <h3>Автор: {{ publication.author }}</h3>
    <h3>Участники:</h3>
    {% for person in publication.person.all %}
        <ul>
            <li><a href="{% url 'core:person_detail' person.pk %}"
                   role="button"> {{ person }}</a></li>
        </ul>
    {% empty %}
        <h3>Связанных личностей нет</h3>
    {% endfor %}

    <h3>Тема публикации: {{ publication.theme.name.title }}</h3>
    <h3>Категория публикации: {{ publication.category.name.title }}</h3>
    <h3>Год: {{ publication.year_start }} {{ publication.year_end }}</h3>
    <h3>Описание:</h3>
    {{ publication.content|linebreaks }}
    <h3>Количество лайков: {{ number_of_likes }}</h3>
    {% if user.profile.pk %}
        <form action="{% url 'core:publication_like' publication.pk %}" method="POST">
            {% csrf_token %}
            {% if post_is_liked %}
                <button type="submit" name="publication_id" value="{{ publication.id }}" class="btn btn-danger">
                    Разонравилось
                </button>
            {% else %}
                <button type="submit" name="publication_id" value="{{ publication.id }}" class="btn btn-info">
                    Понравилось
                </button>
            {% endif %}
        </form>
    {% else %}
        <h4>Необходимо иметь профиль, чтобы оставлять лайки</h4>
    {% endif %}


    {% if user.profile.pk %}
        <a href="{% url 'core:publication_comment' publication.pk %}"> Прокомментировать </a>
    {% else %}
        <h4>Необходимо иметь профиль, чтобы оставлять комментарии</h4>
    {% endif %}

    <h4>Кол-во комментариев: {{ publication.comment_publications.all.count }}</h4>

    {% for comment in publication.comment_publications.all %}
        <ul>
            # {{ comment.pk }}
            <br>

            {% if comment.profile.profile_photo != Null %}
                <img src="{{ comment.profile.profile_photo.url }}" class="img-thumbnail" width="100" height="100">
            {% else %}
                <img src="{% static 'core/images/emptyAvatar.large.jpg' %}" class="img-thumbnail" width="100" height="100">
            {% endif %}
            <br>
            <a href="{% url 'core:user_profile' comment.profile.pk %}"> {{ comment.profile }} </a> - {{ comment.date }}

            {% if comment.parent %}
                <br> Ответ комментарию: {{ comment.parent }}
            {% endif %}

            {% if comment.image %}
                <br> <img src="{{ comment.image.url }}" width="150" height="150">
            {% endif %}
            <br>
            {{ comment.body }}
        </ul>
        {% if request.user.is_superuser %}
        <a href="{% url 'core:publication_comment_delete' comment.pk %}" role="button">Удалить комментарий</a>
        {% endif %}
    {% empty %}
        <h4>Комментариев нет</h4>
    {% endfor %}


{% endblock %}

core/templates/core/publication_update.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser or request.user.is_staff %}
    {% block title %} {{ title }} {% endblock %}
    {% block content %}
        <h1>Обновление публикации "{{ publication.title }}"</h1>
        <form action="{% url 'core:publication_update' pk=publication.pk %}" method="POST"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Обновить</button>
            <a class="btn btn-secondary" href="{% url 'core:publications' %}" role="button">Вернуться</a>
        </form>
    {% endblock %}
{% endif %}

core/templates/core/user_profile_change_role.html
{% extends 'core/base.html' %}
{% if request.user.is_superuser %}
    {% block title %} {{ title }} {% endblock %}
    {% block content %}
        <h1>Сменить роль {{ user.profile.nickname }}?</h1>
        <form action="{% url 'core:user_profile_change_role' pk=user.pk %}" method="POST">
            {% csrf_token %}

            <ul>
                <li><h3>Сделать автором</h3> {{ form.is_staff }}</li>

                <li><h3>Сделать админом</h3> {{ form.is_superuser }}</li>
            </ul>
            <button class="btn btn-danger" type="submit">Сменить роль</button>
            <a class="btn btn-secondary" href="{% url 'core:profiles' %}" role="button">Вернуться к профилям</a>
        </form>
    {% endblock %}
{% endif %}